[package]
name = "mdbook-tailor"
version = "0.6.1"
authors = ["CoralPink <teqt6ytqt@mozmail.com>"]
edition = "2021"
rust-version = "1.70"
description = "mdbook preprocessor for image-tailor"
documentation = "https://github.com/CoralPink/mdbook-tailor/blob/main/README.md"
homepage = "https://github.com/CoralPink"
repository = "https://github.com/CoralPink/mdbook-tailor"
license = "MIT OR Apache-2.0"
keywords = ["mdbook", "image", "tailor"]

[dependencies]
clap = "4.4"
image = "0.24"
mdbook = "0.4"
once_cell = "1.19"
regex = "1.10"
semver = "1.0"
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "1.4.0"

[profile.release]
lto = "thin"
opt-level = 3
strip = "symbols"
