[package]
name = "mdbook-tailor"
version = "0.4.1"
authors = ["CoralPink <teqt6ytqt@mozmail.com>"]
edition = "2021"
rust-version = "1.68"
description = "mdbook preprocessor for image-tailor"
documentation = "https://github.com/CoralPink/mdbook-tailor/blob/main/README.md"
homepage = "https://github.com/CoralPink"
repository = "https://github.com/CoralPink/mdbook-tailor"
license = "MIT OR Apache-2.0"
keywords = ["mdbook", "image", "tailor"]

[dependencies]
clap = "4.2"
mdbook = "0.4"
semver = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
regex = "1.7"
image = "0.24"
